### ISSUE TITLE
Use dynamic length to generate a random number

### ISSUE THREAD

**Issue by anthonydillon** [Jim-Dillon/mid-card-wrestling#1]
When you generate a random number you use the number `10`. Therefore, if you add a new wrestler you will need to update that number.
```js
const randomNumber = Math.floor(Math.random() * 10)
```

When you can make that number dynamic using:
```js
const randomNumber = Math.floor(Math.random() * wrestlers.length)
```

**Comment by Jim-Dillon** [comment]
yep makes sense - have made this change
